INSERT INTO person (first_name, last_name, address, gender, enabled) VALUES
                                                                         ('Morganne', 'Burchall', '1st Floor', 'Female', b'0'),
                                                                         ('Bowie', 'Demeza', 'Apt 1703', 'Male', b'1'),
                                                                         ('Daron', 'Mounter', 'Suite 29', 'Female', b'0'),
                                                                         ('Mahmoud', 'Marchington', 'PO Box 27055', 'Male', b'1'),
                                                                         ('Hayley', 'Sayer', 'Apt 869', 'Female', b'1'),
                                                                         ('Moss', 'Cranmere', 'PO Box 44353', 'Male', b'0'),
                                                                         ('Annelise', 'Mabone', 'Room 237', 'Female', b'0'),
                                                                         ('Gianina', 'Everitt', 'PO Box 73146', 'Female', b'0'),
                                                                         ('Jaquenette', 'Ousley', 'Apt 843', 'Female', b'0'),
                                                                         ('Samantha', 'Ramsdell', 'PO Box 32088', 'Female', b'1'),
                                                                         ('Lalo', 'Marre', 'PO Box 33540', 'Male', b'1'),
                                                                         ('Lark', 'Matityahu', '11th Floor', 'Female', b'1'),
                                                                         ('Marlowe', 'Matteoni', '9th Floor', 'Male', b'0'),
                                                                         ('Gil', 'Duesbury', 'Suite 50', 'Male', b'1'),
                                                                         ('Evered', 'Hargrave', 'Suite 2', 'Male', b'1'),
                                                                         ('Tyrus', 'Robken', 'Suite 82', 'Male', b'1'),
                                                                         ('Lyndy', 'Hughs', 'PO Box 91917', 'Female', b'1'),
                                                                         ('Charlot', 'Petrov', 'PO Box 63861', 'Female', b'0'),
                                                                         ('Kimmie', 'Dingate', 'Suite 28', 'Female', b'0'),
                                                                         ('Karylin', 'Goodacre', 'Apt 738', 'Female', b'1'),
                                                                         ('Miriam', 'Bawle', 'Suite 15', 'Female', b'1'),
                                                                         ('Nappy', 'Greenhaugh', 'Apt 514', 'Male', b'0'),
                                                                         ('Rafaelita', 'Peiser', 'Room 15', 'Female', b'0'),
                                                                         ('Curry', 'Hargreves', 'Room 1014', 'Male', b'0'),
                                                                         ('Langston', 'Chstney', 'Suite 67', 'Male', b'0'),
                                                                         ('Rubia', 'Cornwall', 'PO Box 16167', 'Female', b'0'),
                                                                         ('Moishe', 'Campion', 'Room 331', 'Male', b'0'),
                                                                         ('Mary', 'Swaddle', 'Apt 1300', 'Female', b'0'),
                                                                         ('Jory', 'Beels', 'Room 277', 'Male', b'0'),
                                                                         ('Itch', 'Brood', 'Room 233', 'Male', b'1'),
                                                                         ('Dedra', 'Reynoollds', 'PO Box 17367', 'Female', b'0'),
                                                                         ('Sherlocke', 'Wibrow', 'PO Box 36739', 'Male', b'1'),
                                                                         ('Thayne', 'Savory', 'PO Box 53952', 'Male', b'1'),
                                                                         ('Queenie', 'Boutwell', 'Apt 1140', 'Female', b'0'),
                                                                         ('Tiphany', 'Pieters', 'PO Box 34381', 'Female', b'0'),
                                                                         ('Talbot', 'Lister', 'Room 1547', 'Male', b'1'),
                                                                         ('Seamus', 'Pizey', '15th Floor', 'Male', b'0'),
                                                                         ('Vita', 'Dreakin', 'PO Box 90052', 'Female', b'0'),
                                                                         ('Gennie', 'Vickress', 'Apt 1380', 'Female', b'0'),
                                                                         ('Berke', 'Koba', 'Apt 43', 'Male', b'0'),
                                                                         ('Chiarra', 'Fawbert', 'Suite 62', 'Female', b'1'),
                                                                         ('Jozef', 'Coalbran', 'Room 1632', 'Male', b'0'),
                                                                         ('Ganny', 'Dottridge', 'Room 1200', 'Male', b'0'),
                                                                         ('Kipper', 'Yvon', 'PO Box 61017', 'Male', b'1'),
                                                                         ('Northrup', 'Grabban', 'Suite 98', 'Male', b'1'),
                                                                         ('Franz', 'Breit', 'Room 1316', 'Male', b'0'),
                                                                         ('Parnell', 'Bris', 'Room 322', 'Male', b'1'),
                                                                         ('Brittany', 'Minchell', 'Room 1141', 'Female', b'1'),
                                                                         ('Marleen', 'Jacombs', 'Room 383', 'Female', b'0'),
                                                                         ('Leda', 'Bohey', '1st Floor', 'Female', b'1'),
                                                                         ('Doe', 'McIlwraith', 'Suite 67', 'Female', b'0'),
                                                                         ('Basile', 'Collumbell', 'Suite 76', 'Male', b'0'),
                                                                         ('Jesus', 'Alessandrucci', 'Room 1155', 'Male', b'0'),
                                                                         ('Buddy', 'Cyson', 'Apt 1363', 'Male', b'0'),
                                                                         ('Fax', 'Lilburn', 'Suite 66', 'Male', b'1'),
                                                                         ('Felice', 'Gainseford', 'Suite 77', 'Female', b'0'),
                                                                         ('Rivi', 'Hellcat', 'Apt 1400', 'Female', b'1'),
                                                                         ('Sampson', 'Bowle', 'PO Box 60095', 'Male', b'0'),
                                                                         ('Brigitte', 'Cubbon', 'PO Box 32002', 'Female', b'0'),
                                                                         ('Carie', 'Bing', '16th Floor', 'Female', b'1'),
                                                                         ('Kerri', 'Gatehouse', 'Suite 69', 'Female', b'0'),
                                                                         ('Earl', 'Valentino', 'Room 1013', 'Male', b'0'),
                                                                         ('Remington', 'Weldrake', '16th Floor', 'Male', b'0'),
                                                                         ('Kitti', 'Lawton', 'PO Box 22357', 'Female', b'0'),
                                                                         ('Dayna', 'Tierney', 'Suite 11', 'Female', b'1'),
                                                                         ('Griswold', 'Czadla', '8th Floor', 'Male', b'0'),
                                                                         ('Kay', 'McGourty', 'PO Box 39970', 'Female', b'1'),
                                                                         ('Federico', 'Borleace', '17th Floor', 'Male', b'0'),
                                                                         ('Boniface', 'Le Breton', 'PO Box 25872', 'Male', b'1'),
                                                                         ('Rolando', 'Jindra', 'Suite 75', 'Male', b'1'),
                                                                         ('Lilith', 'Writtle', 'Room 1165', 'Female', b'1'),
                                                                         ('Lezlie', 'Wane', '2nd Floor', 'Female', b'1'),
                                                                         ('Bessy', 'Gercke', 'Room 643', 'Female', b'1'),
                                                                         ('Tyrone', 'Fruish', 'PO Box 60372', 'Male', b'0'),
                                                                         ('Nealy', 'Hockell', 'Suite 28', 'Male', b'0'),
                                                                         ('Ogden', 'Huggens', 'Suite 57', 'Male', b'0'),
                                                                         ('Nani', 'Oylett', 'Room 1736', 'Female', b'0'),
                                                                         ('Monah', 'Kilbourn', 'Suite 79', 'Female', b'0'),
                                                                         ('Kermit', 'Trotter', 'Apt 1614', 'Male', b'1'),
                                                                         ('Alina', 'Phettis', '7th Floor', 'Female', b'1'),
                                                                         ('Henri', 'Crocetto', 'PO Box 73745', 'Male', b'0'),
                                                                         ('Lin', 'Eyckel', 'Suite 70', 'Male', b'1'),
                                                                         ('Cassey', 'Milillo', 'Room 475', 'Female', b'1'),
                                                                         ('Katina', 'Londors', 'Room 346', 'Female', b'0'),
                                                                         ('Kelsi', 'Joselson', '8th Floor', 'Female', b'0'),
                                                                         ('Mitzi', 'Nibloe', 'PO Box 26216', 'Female', b'1'),
                                                                         ('Brynn', 'Checchi', '17th Floor', 'Female', b'0'),
                                                                         ('Homer', 'Tarpey', 'Suite 86', 'Male', b'1'),
                                                                         ('Sadye', 'Stilly', 'Apt 1420', 'Female', b'1'),
                                                                         ('Regina', 'Zannetti', '3rd Floor', 'Female', b'1'),
                                                                         ('Lucian', 'Kearton', '16th Floor', 'Male', b'0'),
                                                                         ('Kerwin', 'Blatchford', 'Suite 9', 'Male', b'0'),
                                                                         ('Emmie', 'Jirka', 'Apt 1780', 'Female', b'0'),
                                                                         ('Haslett', 'Champagne', 'Apt 603', 'Male', b'1'),
                                                                         ('Eadmund', 'Kollatsch', 'PO Box 25026', 'Male', b'1'),
                                                                         ('Matthiew', 'Pren', 'PO Box 64941', 'Male', b'0'),
                                                                         ('Isaiah', 'Grafom', 'PO Box 89861', 'Male', b'0'),
                                                                         ('Toni', 'Pagnin', 'Suite 77', 'Female', b'0'),
                                                                         ('Cyndia', 'Dietmar', 'Apt 953', 'Female', b'1'),
                                                                         ('Guido', 'Mathevet', 'Suite 41', 'Male', b'0');